export enum ActionEnum {
    CREATED = 'CREATED',
    UPDATED = 'UPDATED',
    STATUS_CHANGED = 'STATUS_CHANGED',
    COMMENT_ADDED = 'COMMENT_ADDED',
    USER_ASSIGNED = 'USER_ASSIGNED',
    USER_REMOVED = 'USER_REMOVED'
}